/*USER API CONST*/


export const CHAT_USER_LIST = "CHAT_USER_LIST";
export const CHAT_USER_LIST_REQUESTED = 'CHAT_USER_LIST_REQUESTED';
export const CHAT_USER_LIST_FAILED = 'CHAT_USER_LIST_FAILED';

