/*USER API CONST*/

export const GET_REMAIN_DAYS_DELETE = "GET_REMAIN_DAYS_DELETE";
export const LOGIN_TOKEN = "LOGIN_TOKEN";
export const LOGIN_WITH_SMS = "LOGIN_WITH_SMS";
export const LOGIN_WITH_SMS_SUCCESS = "LOGIN_WITH_SMS_SUCCESS";
export const LOGIN_WITH_SMS_FAIL = "LOGIN_WITH_SMS_FAIL";
export const CHANGE_PHONE = "CHANGE_PHONE";
export const VERIFY_OTP = "VERIFY_OTP";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAIL = "VERIFY_OTP_FAIL";
export const LOGIN_AFTER_VERIFY = "LOGIN_AFTER_VERIFY";
export const CHAT_USER_LIST = "CHAT_USER_LIST";
export const CHAT_INFOR = "CHAT_INFOR";
export const SEND_MESSSAGE = "SEND_MESSAGE";
export const PAYMENT_HISTORY = "PAYMENT_HISTORY";
export const USER_PROFILE = "USER_PROFILE";
export const EDIT_PROFILE = "EDIT_PROFILE";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAIL = "EDIT_PROFILE_FAIL";
export const ADD_SKILLS = "ADD_SKILLS";
export const VIEW_SKILLS = "VIEW_SKILLS";
export const ADD_PORTFOLIO = "ADD_PORTFOLIO";
export const UPDATE_NOTIFICATIONS = "UPDATE_NOTIFICATIONS";
export const NOTIFICATIONS = "NOTIFICATIONS";
export const NOTIFICATIONS_SETTINGS_SHOW = "NOTIFICATIONS_SETTINGS_SHOW";
export const CANCEL_REQUEST_FOR_DELETE_ACCOUNT =
  "CANCEL_REQUEST_FOR_DELETE_ACCOUNT";
export const PUBLISH_REPORT = "PUBLISH_REPORT";

/*POST API CONST*/

export const POST_TASK = "POST_TASK";
export const POST_TASK_SUCCESS = "POST_TASK_SUCCESS";
export const POST_TASK_FAIL = "POST_TASK_FAIL";
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS";
export const GET_ALL_CATEGORY_FAIL = "GET_ALL_CATEGORY_FAIL";
export const STORE_CATEGORY_ID = "STORE_CATEGORY_ID";
export const STORE_CATEGORY_ID_SUCCESS = "STORE_CATEGORY_ID_SUCCESS";
export const GET_MY_POST = "GET_MY_POST";
export const GET_BROWSE_POST = "GET_BROWSE_POST";
export const POST_QUESTION = "POST_QUESTION";
export const POST_QUESTION_REPLY = "POST_QUESTION_REPLY";
export const POST_COMMENT = "POST_COMMENT";


/*TASK API CONST */
export const CHOOSE_TASK = "CHOOSE_TASK";
export const GET_TASK = "GET_TASK";

export * from "./user/actions";
export * from "./category/actions";
export * from "./Post/actions";
export * from "./task/actions";
export * from "./payment/actions";
